### ISSUE TITLE
Switched format strings in periodicFetchData ?

### ISSUE THREAD

**Issue by chrissearle** [airgradienthq/arduino#11]
TMP_RH:

https://github.com/airgradienthq/arduino/blob/master/AirGradient.h#L135-L136

```
      float t;
      int rh;
```

periodicFetchData()

https://github.com/airgradienthq/arduino/blob/master/AirGradient.cpp#L300-L301

```
    sprintf(result.t_char,"%d", result.t);
    sprintf(result.rh_char,"%f", result.rh);
```

Are the format strings there not reversed? t is float and rh is int?

**Comment by airgradienthq** [comment]
This is correct. Only for temperature the sensor gives decimals.
