### ISSUE TITLE
LedBar brightness is not getting low enough:

### ISSUE THREAD

**Issue by airgradienthq** [airgradienthq/arduino#134]
1% is still quite bright on the monitor. I don't think its 1%. This only affects the LedBar. Display looks ok.

local config shows: 
http://airgradient_xxx.local/config

![image](https://github.com/airgradienthq/arduino/assets/68736665/5d27d7bd-71de-440f-a684-b4da2e47d33a)

But from server comes:
...,"ledbarBrightness":1,"displayBrightness":18,"...}

**Comment by pnt325** [comment]
@airgradienthq  Cause sever send `ledbarBrightness` instead of `ledBarBrightness`. So the value is not update any more.
