### ISSUE TITLE
TVOC in display should be in all caps

### ISSUE THREAD

**Issue by MallocArray** [airgradienthq/arduino#139]
Like other sensor names, TVOC should be in all caps, not lower case.

It is an acronym and should be capitalized, as well as matching the formatting of all of the other displayed readings.

Also, I believe it should be VOC instead of TVOC, as that is what the manufacturer refers to it at:
https://sensirion.com/products/catalog/SGP40/

**Comment by pnt325** [comment]
@airgradienthq 
![IMG_1324](https://github.com/airgradienthq/arduino/assets/46193669/77da0bfb-5790-43af-8188-ae21af74d733)

**Comment by MallocArray** [comment]
I like the capitals.

Still think the spacing of the columns could be improved. No reason for all of the blank space to the right of VOC and PM2.5 could still use some extra room.

This is what my ESPHome firmware looks like (Top line wasn't included due to my camera shutter being too fast)

![image](https://github.com/airgradienthq/arduino/assets/9374884/c4aaffdc-9dad-4073-8e41-4dcd2c544222)

**Comment by airgradienthq** [comment]
@pnt325 Please also adjust the layout as @MallocArray suggests. Then make a new pull request.

**Comment by pnt325** [comment]
![d0bde8b4f6fc53a20aed](https://github.com/user-attachments/assets/0214caf5-40bb-4861-81ea-1a3ad60a01d4)

I update the layout for 4 character value of CO2 and 3 character value of PM.

**Comment by MallocArray** [comment]
I like it!

**Comment by airgradienthq** [comment]
@pnt325 Perfect. Let's go with that.

**Comment by pnt325** [comment]
@airgradienthq Please check and aprrove PR #195
