### ISSUE TITLE
PM2.5 display could be wider

### ISSUE THREAD

**Issue by MallocArray** [airgradienthq/arduino#140]
The PM2.5 window in the middle of the display looks oddly squished, especially since there is so much blank space to the far right of `tvoc:`

I also wonder if PM2.5 would properly handle 3 digits, as it looks to only have sufficient space to look good for up to 2 digits. 

What if it needed to display 288?  Feels like it may not fit within the bars, or at least would be very cramped looking.

**Comment by MallocArray** [comment]
CO2 also could/should be wider.  I had it displaying an 8 as the last digit and it looked very uncentered in the column and nearly touching the bar.  Here is a picture after it changed to 9, and while this photo doesn't look at bad, in person, it certainly felt misaligned and like it was running off the side of the column
![image](https://github.com/airgradienthq/arduino/assets/9374884/fdc15f20-3c63-449f-a062-c590ae091536)

**Comment by airgradienthq** [comment]
Closing thus due to duplicate.
