### ISSUE TITLE
Add support for Prometheus/OpenMetrics to One V9 #59 no longer supported

### ISSUE THREAD

**Issue by Kaydron1000** [airgradienthq/arduino#153]
Prometheus/OpenMetrics was supported in earlier versions. This was removed and would be great if it was added again.
@dechamps originally performed the updated.

**Comment by pnt325** [comment]
Hi @Kaydron1000 

What is your issue? It's still supported but the code move to separate file, you find [here](https://github.com/airgradienthq/arduino/tree/develop/examples/OneOpenAir). The example `One.ino` and `OpenAir.ino` has combine into one `OneOpenAir.ino`

**Comment by Kaydron1000** [comment]
I switched back to 3.1.1, and it does work. Maybe I was looking at a different port or something. Thanks for confirming it still exists in there.
