### ISSUE TITLE
'pmStandard' value 'usaqi' invalid

### ISSUE THREAD

**Issue by joostlek** [airgradienthq/arduino#157]
When executing the following request, the server returns with
```txt
'pmStandard' value 'usaqi' invalid
```

```sh
curl --location --request PUT 'http://10.0.0.115/config' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--data '{
    "pmStandard": "usaqi"
}'
```
Even though [the docs](https://github.com/airgradienthq/arduino/blob/master/docs/local-server.md?plain=1#L97) say this should be supported

**Comment by pnt325** [comment]
Hi  @joostlek 
Thank for report. Correct value is `us-aqi`.
