### ISSUE TITLE
[blog] White text on white background

### ISSUE THREAD

**Issue by hestiahacker** [airgradienthq/arduino#158]
The [blog post explaining how to set up the Arduino IDE](https://www.airgradient.com/blog/install-arduino-c3-mini/) has white text on a white background. Below is a screenshot showing this (note the text after the second bullet point)

![white-text-on-white-background](https://github.com/airgradienthq/arduino/assets/116128976/5a715360-ce6c-4b91-9620-84737ddef400)

**Comment by airgradienthq** [comment]
Actually this is an old link. New page is at:
https://www.airgradient.com/documentation/install-arduino-c3-mini/

I added a redirect.
