### ISSUE TITLE
[build documentation] Sketch name appears to be incorrect

### ISSUE THREAD

**Issue by hestiahacker** [airgradienthq/arduino#159]
The [build instructions](https://www.airgradient.com/documentation/overview/) for version 9.0 says the Arduino Sketch Name is OpenAirONE.ino, but this can not be found in the GitHub library linked to on this same page.

![Wrong-sketch-filename](https://github.com/airgradienthq/arduino/assets/116128976/dbf1e68a-037e-4958-91a0-d57466e647b5)

I first looked in the ./src directory and eventually found an example which I believe to be not just an example, but the entire firmware for a production device in the examples directory.

Changing that page to say the Arduino Sketch name is ./examples/OneOpenAir/OneOpenAir.ino and linking to the git repo would make it much less confusing to new users.

Also, it appears that all of the filenames are wrong and some of them don't appear to be in the repo at all. BASIC.ino may be the new name for what was DIY_BASIC.ino, but it's not clear what became of DIY_OUTDOOR and all the DIY_PRO ino files.

**Comment by airgradienthq** [comment]
@hestiahacker Thanks for reporting. Implemented on https://www.airgradient.com/documentation/overview/
