### ISSUE TITLE
LED inconsistency | Firmware v. 3.1.1

### ISSUE THREAD

**Issue by yegormk** [airgradienthq/arduino#161]
I've noticed some issues with the LED bar:
The pictures might not be very clear, but you can see green lights on the first and last LED lights, and in the middle, they are all yellow.
Maybe all LEDs should be yellow and not: "green | yellow | yellow | yellow | green" ? 

![Ticket1](https://github.com/airgradienthq/arduino/assets/82291871/d4efccdb-4096-4bf5-bdf8-3407f37ff09e)
![Ticket2](https://github.com/airgradienthq/arduino/assets/82291871/0464ed72-cc2d-4fb6-8221-02864fb9e9f9)

There also could be some issues on other levels.

**Comment by pnt325** [comment]
@yegormk 
As for your  CO2 value and number of LED is turn off the LED color should be `Organge`

**Comment by yegormk** [comment]
@pnt325 Yes, that is correct. 
But the colors on the first and last LEDs lamps are _Green_ and not _Orange_.
Maybe these two also should be _Orange_?

**Comment by pnt325** [comment]
> @pnt325 Yes, that is correct. But the colors on the first and last LEDs lamps are _Green_ and not _Orange_. Maybe these two also should be _Orange_?

Thank for your report. I'll check it.

**Comment by airgradienthq** [comment]
@yegormk Could you please check if that issue still exists with fw 3.1.4?

**Comment by yegormk** [comment]
@airgradienthq @pnt325 
Issue is still there 
![image](https://github.com/airgradienthq/arduino/assets/82291871/48ebe41a-ccfb-41cc-86d3-3286fbd60909)
![image](https://github.com/airgradienthq/arduino/assets/82291871/6ae4e664-06fe-4e9b-99b9-b285a22a369c)

I have Firmware version 3.1.4:
![image](https://github.com/airgradienthq/arduino/assets/82291871/9cdbead5-a6e8-4ef1-92f7-2e2d86816d55)

Could you please check on your devices?

**Comment by pnt325** [comment]
hi @yegormk 
Thank for your detail report. I have update color code #196 it look better now.
