### ISSUE TITLE
Add boot to keep HA integration compatability

### ISSUE THREAD

**Issue by airgradienthq** [airgradienthq/arduino#168]
Our current HA integration expects "bootCount" as a parameter. However for the airgradient server API we need "boot".

Local server on monitor for the time being should therefore return **both** properties: "boot" and "bootCount".

http://192.168.1.xxx/measures/current
{"wifi":-38,"serialno":"84fce61-----", ... ,"boot":2,"**bootCount**":2, ...}

At a later stage we will adjust the HA integration and depreciate "bootCount".

**Comment by pnt325** [comment]
@airgradienthq  it's ready here #169 

Please check and merge the PR
