### ISSUE TITLE
"CO2 Successfully Initialized. Heating up for 10s"

### ISSUE THREAD

**Issue by Jehn84** [airgradienthq/arduino#17]
Hi! I see "CO2 Successfully Initialized. Heating up for 10s" message after "ag.CO2_Init"  in my code. Where can i change this 10 sec value?

**Comment by Aivaras-s** [comment]
https://github.com/airgradienthq/arduino/blob/master/AirGradient.cpp#L589

**Comment by airgradienthq** [comment]
In v3+ of the library you can change the delay in the example code. E.g. line 232 for the ONE_I-9PSL example.
