### ISSUE TITLE
Unable to change configurationControl

### ISSUE THREAD

**Issue by joostlek** [airgradienthq/arduino#174]
My monitor is set to `local`, but when executing:
```sh
curl --location --request PUT 'http://10.0.0.115/config' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--data '{
    "configurationControl": "cloud"
}'
```
It will return
```txt
Monitor set to accept only configuration from the cloud. Use property configurationControl to change.
```
Which is strange because I am doing what it's telling me to do

**Comment by pnt325** [comment]
@joostlek 
Thank for reporting, that should be success after changed from `local` to `cloud` with that message.

That message indicate you that after change to `cloud` the configuration only change from cloud, all local configuration will be ignore and return failed excepted `configurationControl `

**Comment by joostlek** [comment]
But I would expect that after such request I would get a 200 and know the request itself has been successful. I did notice the lights on my device turned on, so I'm assuming it's fetching data from the cloud, so the request itself worked

**Comment by pnt325** [comment]
> But I would expect that after such request I would get a 200 and know the request itself has been successful. I did notice the lights on my device turned on, so I'm assuming it's fetching data from the cloud, so the request itself worked

That is the issue. I will update it soon.

**Comment by joostlek** [comment]
Ooh check, I didn't interpret your comments as an acknowledgement of the issue but as an explanation that it was expected behaviour. Thanks :)

**Comment by pnt325** [comment]
@joostlek 
Please check PR #175.  And open the issue if still problem

Thanks
Phat

**Comment by joostlek** [comment]
Thanks for helping out!
