### ISSUE TITLE
Senseair S8 lacks error checking (CRC) resulting in bad data

### ISSUE THREAD

**Issue by npfusaro** [airgradienthq/arduino#18]
getCO2_Raw simply looks for a value of 254 in the first byte to check if a packet is good. Then parses bytes in the array slots 3 and 4 into a value. 
A standard response from the S8 is Array[] { 0xFE, 0x68, 0x02, 0xXX, 0xXX, 0xXX , 0xXX }
 
The data in the 4th and 5th bytes are the CO2 response value while the bytes in the 6th and 7th are the CRC. 

If this data stream is out of sync the simple check for the “Any sensor” address in the first byte can cause you to report an incorrect value of 17410. I have seen this issue on my sensor multiple times. Implementing a CRC check would validate the data an prevent bad values from being sent.

**Comment by d3vilh** [comment]
Here is improved firmware: https://github.com/d3vilh/airgradient-improved
