### ISSUE TITLE
firmware versions and relevant boards

### ISSUE THREAD

**Issue by Tom-Neverwinter** [airgradienthq/arduino#180]
for those of us who have older boards it doesnt seem like we are getting support anymore and the naming convention is extremely confusing.  the board is less than a year old 2023-08-08 is the order date for the board and enclosure on jlpcb

https://www.airgradient.com/documentation/diy/
PCB version 3.0
-----------------------------------------------------------------------------------------------------
https://www.airgradient.com/documentation/diy-pro/
he AirGradient DIY Air Quality Sensor (Pro Version PCB Version < 3.7) 
PCB version 3.7
PCB version 4.2

-----------------------------------------------------------------------------------------------------
https://www.airgradient.com/documentation/firmwares/

https://www.airgradient.com/documentation/one-v9/#firmware

8PSL
8PSLM
8PSL-DE

I-1DIY    Open Air O-1PST?

O-1DIY    Open Air O-1PST?

I-9PSL    AirGradient ONE I-9PSL?
I-9PSL-DE AirGradient ONE I-9PSL?

O-1PP  Open Air O-1PST?
O-1PPT Open Air O-1PST
O-1PS  Open Air O-1PST?
O-1PST Open Air O-1PST

airgradient basic
AirGradient ONE I-9PSL
Open Air O-1PST and O-1PP(T) models

**Comment by airgradienthq** [comment]
@Tom-Neverwinter 
The following models are already supported:
- AirGradient ONE I-9PSL
- Open Air models O-1PP, O-1PPT and O-1PST

We are currently working on supporting the following older models:
- DIY-BASIC
- DIY-PRO-4.3
- DIY-PRO-3.7

First test firmware versions could already be available in a week's time.

For the other models, we need to see how much demand is there and then see how we can support them (we are quite stretched with resources).

**Comment by epragalakis** [comment]
@airgradienthq any updates on that? (I'm interested in the DIY-PRO-3.7)
