### ISSUE TITLE
PCB 4.3: Wrong model name

### ISSUE THREAD

**Issue by airgradienthq** [airgradienthq/arduino#185]
measures/current from local server returns model:

    "model": "I-8PSL"

Should be: 

    "model": "DIY-PRO-I-4.3PS"

See also:
https://github.com/airgradienthq/python-airgradient/issues/107

**Comment by pnt325** [comment]
Firmware mode is updated:
https://github.com/airgradienthq/arduino/blob/7d15c37ad9f4d7cb8ce8f7c227552c522efefdd2/src/App/AppDef.cpp#L17-L22

The model name get from cloud is `8PSL`?

**Comment by airgradienthq** [comment]
Ok, I will check on our backend. So you send model name that you get from cloud in local server? 
What happens if no cloud connection? What model name is then used?

**Comment by pnt325** [comment]
it's send the firmware mode not model name.
