### ISSUE TITLE
Rename Example File DiyIndoorProV3_7

### ISSUE THREAD

**Issue by airgradienthq** [airgradienthq/arduino#189]
We should rename DiyIndoorProV3_7 to DiyIndoorProV3_7 to **DiyIndoorProV3_3** because only 3.3 and before do not have the push button.

3.7 has a push button but is differently wired from 4.2.

Please rename on:
File/Directory name of example file
Identifier for PCB/model in code

**Comment by pnt325** [comment]
@airgradienthq  schematic of DIY-Pro 3.7. Now I rename example 3.7 to 3.3 wait for you schematic to add new example for 3.7

**Comment by airgradienthq** [comment]
We will not have 3.7 right now.
