### ISSUE TITLE
Prevent  "postDataToAirGradient": null

### ISSUE THREAD

**Issue by airgradienthq** [airgradienthq/arduino#220]
We have cases when "postDataToAirGradient": null.
Model O-1PPT

This should not happen.

@pnt325 Please investigate and fix.

{
    "country": "TH",
    "configurationControl": "local",
    "pmStandard": "ugm3",
    "temperatureUnit": "c",
    "postDataToAirGradient": true,
    "ledBarBrightness": 95,
    "displayBrightness": 14,
    "ledBarMode": "pm",
    "tvocLearningOffset": 360,
    "noxLearningOffset": 720,
    "abcDays": 1,
    "model": "O-1PPT",
    "offlineMode": false,
    "postDataToAirGradient": null
}

**Comment by pnt325** [comment]
@airgradienthq 
Did you have log message from device for this case. Currently the read data from EEPROM/SPIFFS and write configuration value always validate. The value should not happen for `null`. 

I try some case with some invalid valid but it's ignored:
- Erase device then load empty data, all configuration load to default `true`
- Configuration on WiFi setup
- Configuration on local API

Invalid value ignore log message
```
'postDataToAirGradient' type invalid, it's should 'boolean'
```
