### ISSUE TITLE
Documentation: Select "D1 mini (clone)"

### ISSUE THREAD

**Issue by gohai** [airgradienthq/arduino#27]
The instructions [here](https://www.airgradient.com/open-airgradient/instructions/basic-setup-skills-and-equipment-needed-to-build-our-airgradient-diy-sensor/) mention selecting a "Lolin (Wemos) D1 Mini board", but current versions of the ESP8266 toolchain for Arduino have multiple sub-variants with different amount of flash memory.

The D1 mini (clone) appears to match the board that comes with the kit (4MB flash).

<img width="466" alt="airgradient" src="https://user-images.githubusercontent.com/4945451/221386104-2c732254-89ea-4738-96f1-0af57dd5477e.png">

**Comment by airgradienthq** [comment]
Yes this board can be used.
