### ISSUE TITLE
Offset temperature of SHT3X sensor

### ISSUE THREAD

**Issue by hundredfire** [airgradienthq/arduino#29]
Hello. I'm a complete noob cf arduino but I managed to complete this nice build thanks to your instructions. I now have an airgradient basic package that sends readings to a Grafana dashboard. Very nice

However, like many users (from what I've read), I noticed that the SHT31 sensor that I'm using, is offset by 0.6-1 degrees celsius. From the investigations of some users on the airgradient forum, it seems that it is caused by the wemos d1 chip itself, transmitting its heat through conduction through the wires themselves.

I've tried mitigating this issue by wiring the sht31 using long cables to the airgradient pcb and secluding the sensor out of the enclosure and air-tightening it from the rest of the components. But there is still some 0.6-1 degrees too much.

So would it be possible to implement an offset to the temperature reading inside of the airgradient.h library?

**Comment by airgradienthq** [comment]
Temperature compensation has been implemented in the Open Air. The ONE does not need it.
