### ISSUE TITLE
What is the License?

### ISSUE THREAD

**Issue by sbquinlan** [airgradienthq/arduino#32]
The root LICENSE on the repo is MIT. The header on the files is [CC BY-SA 4.0 Attribution-ShareAlike 4.0 International License](https://github.com/airgradienthq/arduino/blob/master/examples/DIY_PRO_V4_2/DIY_PRO_V4_2.ino#L27). Is the intention that the example content is CC and the library is MIT?

**Comment by airgradienthq** [comment]
Complete library is CC BY-SA 4.0 Attribution-ShareAlike 4.0 International License. Updated in release 3.0.
