### ISSUE TITLE
Some improvements for the display output

### ISSUE THREAD

**Issue by ciriousjoker** [airgradienthq/arduino#34]
In [my fork](https://github.com/ciriousjoker/airgradient) of this library for the 4.2 pro, I've made these improvements:
- Switch to unicode font
  - CO2 -> CO₂
  - PM -> PM₂₅
- NOX -> NOx
- Limit temperature to 1 instead of 2 digits precision
- Optional compile time flag for minimum brightness
- Vertically align the values correctly
- Fix version comment at the top of the file (said 3.7 previously)

**Should I create PRs for (some of) these changes?**

### Result (full brightness):
![image](https://github.com/airgradienthq/arduino/assets/16866223/d89bc2ef-90af-4df6-9c6d-39dde895329c)

**Comment by airgradienthq** [comment]
Please check version 3 of the library. Some of the items have been addressed but not all due to font character restrictions. Feel free to make a PR based on the latest version of the library.

**Comment by ciriousjoker** [comment]
Unfortunately I switched to esphome + home assistant, which means my fork is practically dead since I don't have time to maintain it.

This can be closed, although I'll leave my fork up for now, in case someone else finds the time to rebase the changes onto the latest version of this library.
