### ISSUE TITLE
No NOx value

### ISSUE THREAD

**Issue by oxivanisher** [airgradienthq/arduino#55]
I upgraded my AirGradient One V9 from 3.0.0 to 3.0.1 trough the [www.airgradient.com/documentation/one-v9/](https://www.airgradient.com/documentation/one-v9/) page and realized that I now don't get a `noxIndex` value from the API from airgradient.com. Then I found the [www.airgradient.com/documentation/factory/](https://www.airgradient.com/documentation/factory/) page where 3.0.2 is available, but flashing this also did not fix the missing nox value. It is shown on the sensor display.

* Where should I post this? Since I did not change anything else than the firmware, I think this has to be the reason.
* Where is the correct place to find the actual latest (stable) firmware?

**Comment by oxivanisher** [comment]
Currently I don't get the `nox_index` field from the airgradient API. But this might be because of the firmware version?
So my question remains: Where is the correct place to find the actual latest (stable) firmware?
Do I have to compile it myself for the bought AirGradient ONE V9?

**Comment by pnt325** [comment]
> Currently I don't get the `nox_index` field from the airgradient API. But this might be because of the firmware version? So my question remains: Where is the correct place to find the actual latest (stable) firmware? Do I have to compile it myself for the bought AirGradient ONE V9?

Currently you are only get the lasted and stable firmware by compile the `ONE_I-9PSL.ino` example. On this example of version `3.0.4` you can get the data over `noxIndex`.

**Comment by pnt325** [comment]
Here is newest firmware you can easy flash to your device: [3.0.5-beta](https://www.airgradient.com/documentation/firmwares/)

**Comment by oxivanisher** [comment]
It is still confusing where and how new firmwares are linked for download, but on this url, https://www.airgradient.com/documentation/firmwares/ there is now even a 3.0.7 and it seems that my initial problem is solved, so closing this issue.
