### ISSUE TITLE
SensAir S8 - enable/disable the automatic calibration

### ISSUE THREAD

**Issue by SunboX** [airgradienthq/arduino#6]
Hi,

is there a way to enable or disable the automatic baseline calibration?

By default, is it enabled or disabled?

**Comment by sensovision** [comment]
As far as I know it's enabled, and I was also trying to find the answer on how to disable it, have you ever found out?

**Comment by airgradienthq** [comment]
It is enabled by default. We currently add a feature to change the ABC period or switch it off. Should be available in one of the next versions.
