### ISSUE TITLE
Server POST toggle in firmware configuration

### ISSUE THREAD

**Issue by tykling** [airgradienthq/arduino#82]
Hello,

Thank you for a great product.

The new Prometheus `/metrics` endpoint is great, so I no longer need to `POST` periodically to a server. But the code requires successful `POST` to the server URL or it turns on an error LED.

Would it be possible to make periodic server `POST` reporting configurable in the server config? Then people can disable it if they don't need it.

Thanks! :)

**Comment by pnt325** [comment]
Hi @tykling 

You can find on code and comment this line:
```c
serverSchedule.run();
```

**Comment by tykling** [comment]
Hello,

Thank you for that.

I know I can disabe it in the code, but I would love to be able to turn it off in the serverconfig. Any chance of adding this? 

The server POST url could be made configurable in the serverconfig, and if left blank it could disable server POST entirely (including the error logic).

Thoughts? Thank you! :)

**Comment by pnt325** [comment]
Hi @tykling 
Thank for advice. 

Currently we don't support it from server configuration.
I will discuss with team about it.

Thanks
Phat

**Comment by airgradienthq** [comment]
We plan to add this as part of the configuration of the monitor. So that a PUT can be set to toggle the communication with the AirGradient servers.

**Comment by airgradienthq** [comment]
This has been addressed in the latest firmware release.
