### ISSUE TITLE
functionality ceased?

### ISSUE THREAD

**Issue by Tom-Neverwinter** [airgradienthq/arduino#89]
The AirGradient DIY Air Quality Sensor (Pro Version PCB Version < 3.7) ceased showing voc or tvoc with SGP41 sensor

**Comment by airgradienthq** [comment]
Which firmware version are you running?

**Comment by Myrmi123** [comment]
I also noticed this. In the 2.4.x version there was an example file for the PCB 4.2 (now called Basic?) which included code for the NOx sensor. This is now missing in the "Basic" example.

**Comment by airgradienthq** [comment]
There is a new version in 3.1.4 for PCB 4.2 that supports VOC/NOx.
https://github.com/airgradienthq/arduino/tree/master/examples/DiyProIndoorV4_2

**Comment by airgradienthq** [comment]
@Tom-Neverwinter Can you please link to that documentation so that we can update it?
